# Generated by Django 4.2.7 on 2024-03-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('Image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, verbose_name='عنوان تصویر')),
                ('img', models.ImageField(default=None, upload_to='images/', verbose_name='بارگزاری تصویر')),
                ('Image_description', models.CharField(max_length=1000, verbose_name='توضیحات عکس')),
                ('Image_category', models.CharField(choices=[('cars', 'خودرو'), ('animation', 'انیمیشن'), ('abstract', 'اجسام سه بعدی'), ('nature', 'طبیعت'), ('space', 'فضا'), ('movies', 'فیلم'), ('games', 'بازی های ویدیویی'), ('typography', 'تایپوگرافی'), ('architecture', 'معماری'), ('fashion', 'فشن')], max_length=100, verbose_name='دسته بندی عکس')),
                ('image_owner_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('password', models.CharField(max_length=50, verbose_name='رمز عبور')),
            ],
        ),
    ]
